### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Teun** [SimpleBrowserDotNet/SimpleBrowser#126]
We really need a better story for documentation and tutorial. Especially having a tutorial detailing what SimpleBrowser can and cannot do. I've made a start in the github wiki at https://github.com/axefrog/SimpleBrowser/wiki/Tutorial

**Comment by kevingy** [comment]
Added a section on working with and submitting forms.

**Comment by Teun** [comment]
Added a part on Request Logging

**Comment by kevingy** [comment]
Added a section on basic authentication.

**Comment by kevingy** [comment]
This issue is too vague. There is no acceptance criteria to know when it's "done". Since it's been open for 4.5 years, I'm going to consider it done. If/When more documentation is needed, we can add new issues with specific acceptance criteria for adding documentation.
