### ISSUE TITLE
Transfer of project ownership

### ISSUE THREAD

**Issue by axefrog** [SimpleBrowserDotNet/SimpleBrowser#142]
Hey guys, just wanted to quickly explain the shift of ownership from my Github account to a new "SimpleBrowserDotNet" account. You both (kevingy/Teun) have maintained this project for a long time now and probably put far more work into it than I ever did, so I have come to view it as a project with shared ownership; I do not feel I own the project any more than you guys do, and especially given the fact that I have had almost no need for it for a long time now, it felt right to umbrella the project under a more explicitly shared name, and to have you both properly acknowledged as full-rights administrators. In this way, you can make any decisions you feel are right for the project, including giving other people commit rights and so forth. I'll stick around of course, but executive decisions regarding the direction of the project are entirely up to you. Please don't ever feel the need to ask me for the go-ahead on any decisions you want to make or directions you want to take with the project. And thanks for all the great work you put in; NuGet shows over 10000 installs, so clearly it's been useful to others!

**Comment by kevingy** [comment]
Hi Nathan, Thank you for the time and effort you put into SimpleBrowser and getting the project started. When I found SimpleBrowser, it was (and still is) the best tool available for what it is and what it does. Hopefully you will stick around and check in occasionally. I'll do my best to continue to work on SimpleBrowser and guide it in a positive direction. Thank you, Kevin

**Comment by axefrog** [comment]
@kevingy You're welcome. I built it originally to scratch an itch. There wasn't anything else out there at the time. I'm glad it has been able to live on and be of use to others. And definitely I am not going anywhere, I'll always be around to see how things are going.

**Comment by Teun** [comment]
I must say that the time when working on SimpleBrowser was fulfilling my own daily needs is over for me as well. My current work is generally very javascript-heavy, so when I do browser testing, I use PhantomJS. However, I do use SimpleBrowser every now and then to do some quick scraping. 
Maybe I should also transfer my SimpleBrowser.WebDriver package to this account?

**Comment by DriveU** [comment]
I think the WebDriver should be part of this project. Teun and Kevin should make this a strong alternative for PhantomJS. If the SimpleBrowser Webdriver is updated with a new build I am working on Fiddler attachment that can be Opened to the community too as a SimpleBrowser side dish.
