### ISSUE TITLE
Setting up the SimpleBrowserDotNet organization

### ISSUE THREAD

**Issue by Teun** [SimpleBrowserDotNet/SimpleBrowser#143]
So what more should be done? 
1. I want to hand over the WebDriver project to this same organization. I just forked it to this account, but maybe there is a better way. I see the the SimpleBrowser project has been moved with issues and everything. How do I do that?
2. Continuous Integration. I've updated both projects to watch the SimpleBrowserDotNet URL of Github for building and creating packages.
3. About Nuget: when should we publish new packages? Currently this is a manual process. It happens in TeamCity, but must be manually started. Is that still the best way? Should we automatically publish a packages when a commit is pushed to master and successfully built? The Nuget package of SimpleBrowser is currently 5 months old.

**Comment by axefrog** [comment]
You have to go into your project settings, scroll down to the part that says "Danger Zone", and then click "Transfer Ownership". Naturally I would suggest deleting the fork before you do this.

I'll leave #2 and #3 to Kevin, as I never had any involvement in the deployment/nuget side of things.

**Comment by jbuedel** [comment]
Concerning #3, I think we should automatically build and test every push on any branch. We should build, test, and nuget publish all pushes to master.

Whatever you decide, I'd be happy to help set up/migrate the build server stuff.

**Comment by Teun** [comment]
I have now properly transferred the SimpleBrowser.WebDriver repo to the organization. 

The TeamCity setup is now to automatically publish build results to nuget.org after a successful build on the master branch. I'm not sure how to make TeamCity build all branches and I'm not even sure how important that is. You can run the steps locally before pushing. We could also set up a candidate branch that we do have under CI and merge there first and after successfully passing CI merging to master.

**Comment by jbuedel** [comment]
Building all branches provides a check for when the developer has pushed a commit that only builds and passes tests on their local machine. They missed a file, or a unit test uses a localhost url, that sort of thing. Otherwise those issues might not surface till the code hits master. 

If you choose to do this, enable it by adding a VCS build trigger with a wildcard for the branch name.

**Comment by kevingy** [comment]
Sorry I'm late joining the thread. I have been on vacation.

From what I can tell, #2, the continuous integration item, was a statement, not a question? If not, continuous integration should be a part of the process. What is the issue?

Concerning when to push to Nuget, I suggest keeping this a manual process. There have been a couple times where bad code has been committed to Master. If you will recall @Teun, there was a (IMO, inappropriate) change recently that broke backward compatibility. If this change had been immediately pushed to Nuget and consumers had set their projects up to automatically download packages, there would have been a lot of angry developers.

Additionally, when a Nuget release is created manually, whoever creates the package should also create a tag in Git to indicate the version of the source code that goes with the Nuget release.

If Nuget pushes are kept as a manual process, someone will have to keep track of when it's time for a Nuget release. I volunteer for being responsible for keeping track of updates and kicking off a Nuget release when needed.

**Comment by Teun** [comment]
That's why I suggested that we might set up a 'candidate' branch that is use to accept pull requests and to test. Then when someone (you, if you want) decides that it is time for a new release to nuget, you merge to master and after a successful build and test, the new version is pushed to nuget.org.

But of course, having only a master branch and start the nuget publication manually is also an option. I don't really care for either. 

You can als publish prerelease versions to nuget.

**Comment by kevingy** [comment]
I apologize. I missed your suggestion concerning a candidate branch. I think it's enough to handle it manually, however. We don't have a large number of changes to manage. In the last 5 months, I see just over a dozen commits to master, and many of those aren't code changes. It just seems like more trouble than it's worth at this time.

What do I need to kick off a Nuget package?

**Comment by Teun** [comment]
Create an account for yourself on http://teamcity.codebetter.com/ I can make you project admin (I think) and then publishing a Nuget package is just clicking a button.

**Comment by kevingy** [comment]
I've created my Teamcity account. My username is kevingy.

**Comment by Teun** [comment]
I've made you project Admin.

2015-12-08 14:37 GMT+01:00 Kevin Yochum <notifications@github.com>:

**Comment by romeosr** [comment]
how to run tinder auth.....contrack me my skype:::: romeo.sagor

**Comment by kevingy** [comment]
Closing this issue. After two years, I think the SimpleBrowserDotNet organization is setup up.
