### ISSUE TITLE
mono parse html fails

### ISSUE THREAD

**Issue by elibyy** [SimpleBrowserDotNet/SimpleBrowser#146]
hey there,
your library is running awesome on windows but on mono it breaks
because of the following code

```if(this._doc.DocumentType != null) {
    this._doc.DocumentType.InternalSubset = null;
}```

since mono throws exception https://github.com/mosa/Mono-Class-Libraries/blob/master/mcs/class/System.Xml.Linq/System.Xml.Linq/XDocumentType.cs#L89

**Comment by kevingy** [comment]
I'll be happy to look at it. Can you provide either the URL of the page you are accessing or the source (at least the doctype declaration) of the rendered page? The more you help me, the easier it is for me to help you.

The code you have quoted as being the problem code was actually added to prevent a previous error. It could be that mono has fixed the problem in their code to properly handle doctypes.

**Comment by kevingy** [comment]
Looking at the code, it would appear that you do not have the most current version of the SimpleBrowser code. The tip of DocumentBuilder.cs has:

```
if (_doc.DocumentType != null)
{
#if !__MonoCS__
	_doc.DocumentType.InternalSubset = null;
#endif
}
```

Pull the most current version of SimpleBrowser and your problem should be fixed.

I'm going to close this issue. If it does not go away, please respond with more information and re-open the issue. Thanks!

**Comment by elibyy** [comment]
Hey. So 
A.  I have Had the latest version from nuget. 
B. I've removed the nuget package and downloaded the source with the above line, which by the way as shown my the disassembly browser was not there. But it was not enough so I've added

```Type.GetType("Mono.Runtime") == null```
