### ISSUE TITLE
Add a TakeScreenshot [Request]

### ISSUE THREAD

**Issue by Nonobis** [SimpleBrowserDotNet/SimpleBrowser#147]
Hello,

Could you add a take screenshot for full page or specific element like on selenium ?

Maybe a function like : 

browser.TakeScreenshot() => return image

and for elements :

browser.FindElements(ElementType.TextField, FindBy.Name, "txtMessage").TakeScreenshot(); => return image

thanks by advance.

**Comment by kevingy** [comment]
The short answer is "No". SimpleBrowser does not have a user interface or rendering engine.

The long answer is "Maybe, but unlikely". It depends on what you want the screen capture to look like. Are you expecting the image to look anything like what the output from Chrome or IE might look like? If so, the answer is definitely "No". (See above, SimpleBrowser has no user interface or rendering engine.)

When typical browsers download a page, they download all of the required resources to render that page - the images, CSS, JavaScript, etc. SimpleBrowser doesn't download any of that. All SimpleBrowser has to render is the visible text from the root document returned from the server. It might be possible to render that content, however, the output would look very much like the output from the text-only Lynx browser. Is that what you are looking for?

Regarding rendering form elements, the answer is "probably, yes". My question in return is "Why would I want to do this?" Can you explain how this is useful? For example, why would you want a text box rendered? Isn't it just a rectangular image with the visible text in a box? How is that helpful? Isn't it easier to examine the content of the text box by actually accessing the value of the text box?

```
browser.FindElements(ElementType.TextField, FindBy.Name, "txtMessage").Value;
```

I mean, once you have the image of a text box in your hand, what do you do with it?

**Comment by Nonobis** [comment]
I am more in the first case (screenshot of whole page). 
I would like a image of complete page or a elements (label / div etc ..) for a specific program.

Since my post, i have pulled the source and ... i now know it's not possible :( No webbrowser or custom render engine . There is only request in SimpleBrowser. Great but not great for my current need.

Maybe with a dirty patch on a fork with a dll like HtmlRender ... (https://github.com/ArthurHub/HTML-Renderer)

Thanks for your great response.
