### ISSUE TITLE
Is it possible to use proxy with SimpleBrowser?

### ISSUE THREAD

**Issue by MINDoSOFT** [SimpleBrowserDotNet/SimpleBrowser#150]
First of all thank you for this very useful library.

I am trying to use SimpleBrowser in combination with the library TorSharp
https://github.com/joelverhagen/TorSharp
Is it possible to use this library as a proxy to execute the requests from SimpleBrowser?

Thank you in advance.

**Comment by kevingy** [comment]
In general, SimpleBrowser supports HTTP proxies. That said, I have not attempted to use TorSharp. My answer is, therefore, a cautious yes.

From the example on the TorSharp home page:
```
// execute
var proxy = new TorSharpProxy(settings);
var handler = new HttpClientHandler
{
    Proxy = new WebProxy(new Uri("http://localhost:" + settings.PrivoxyPort))
};
var httpClient = new HttpClient(handler);
await proxy.ConfigureAndStartAsync();
Console.WriteLine(await httpClient.GetStringAsync("http://icanhazip.com"));
```
SimpleBrowser would replace the HttpClientHandler. You should be able to do something like this:
```
var proxy = new TorSharpProxy(settings);
await proxy.ConfigureAndStartAsync();

Browser b = new Browser();
b.SetProxy(new WebProxy(new Uri("http://localhost:" + settings.PrivoxyPort)));
b.Navigate("http://icanhazip.com");
Console.WriteLine(b.ResponseText);
```
Please give that a try and reply. One way or another, I'd like to know if it worked.

**Comment by kevingy** [comment]
@MINDoSOFT - Have you tried this yet? Did it work?

**Comment by MINDoSOFT** [comment]
Hello there Kevin!
Thank you for your prompt reply and detailed answer (with code!). Unfortunately I did not get a chance to try it. But be sure that once I try it I will let you know!

**Comment by MINDoSOFT** [comment]
I managed to try your solution and it works (using the code that you provided).

Marking this question closed.

Thanks again!
