### ISSUE TITLE
pre elements loose their newlines/whitespace

### ISSUE THREAD

**Issue by twpol** [SimpleBrowserDotNet/SimpleBrowser#156]
It seems that SimpleBrowser is trashing the whitespace within `<pre>` elements, which is unfortunately affecting the pages I am trying to process. The text node inside a `<pre>` element should be unaltered from the source (except for exactly 1 leading and trailing newline to be removed IIRC, but that's not important to me).

Looking at the code, I suspect it just needs "pre" adding to the condition with "textarea" here: https://github.com/SimpleBrowserDotNet/SimpleBrowser/blob/f7bbdb2d4cba82105e9831036bc8923b6ad9cca7/SimpleBrowser/Parser/DocumentBuilder.cs#L152

Thanks for a great library, hope this is easily fixed.

**Comment by kevingy** [comment]
I will investigate this later today or early tomorrow. I don't think it will be difficult.

**Comment by kevingy** [comment]
I just submitted a change to fix the <pre> element. If you fetch from the repository, you will get the change. Please let me know if it worked or not.

**Comment by kevingy** [comment]
@twpol Have you had an opportunity to try this fix?

**Comment by twpol** [comment]
@kevingy Assuming building `SimpleBrowser.sln` and linking to `SimpleBrowser\bin\Debug\SimpleBrowser.dll` is what I should be doing, it seems to work. Thanks. :)

**Comment by kevingy** [comment]
That is correct. This change will be in the next Nuget build, when it becomes available.
