### ISSUE TITLE
Proper form for avoiding a leak of Browser instances

### ISSUE THREAD

**Issue by bledbet** [SimpleBrowserDotNet/SimpleBrowser#161]
Hello - apologies if there is reference material somewhere that should answer this question - I looked and could not find an answer to my question.

I have a complex set of browser automations.  In a given automation, I have to call Browser.Navigate multiple times - navigate to the log in page, submit the credentials form there, navigate to another page, do some screen scraping, navigate to another page and use the scraped data to submit another form, etc.  The process using this instance of Browser is long-running, and re-uses the main browser instance by logging out, logging in as another user, and performing similar workflows.  There is a reasonable spot for me to call Close on my main browser instance, but there are cases where I may need to perform hundreds of navigations before I would would to dispose of my main browser instance (because the login and screen scraping at the front end of the workflow is expensive).

Using JetBrains dotMemory, I have discovered a lot more instances of Browser surviving GC's than expected.

The website that I am automating makes a lot of unnecessary use of iframes.  What I am gathering form your source is that SimpleBrowser is creating child Browser instances for those iframes, and keeping them in a collection - the growth in this collection is effectively a big "leak" for me.  

My question is what is the best way for me to be cleaning up these child browser instances?  Do I need to, say, check Browser.Frames and call Close on each browser in that list before I call Navigate on my main browser instance?

**Comment by kevingy** [comment]
I have an application that has been running SimpleBrowser 24/7 (constantly) for about 8 months, performing approximately 1,500 tasks per day. I haven't seen any increase in the memory footprint over that time. My typical execution path for each task is:

1. Create a Browser object
2. Perform typically 2 navigations (request page, fill form, submit page)
3. Clean-up, destroying the Browser

The last thing I do in each task is:
```
if (browser != null)
{
    Browser.ClearWindows();
    browser.Close();
}
```

There are a couple tasks to rework how SimpleBrowser handles memory and leaks. Improving memory management and making these calls unnecessary is on the roadmap.

**Comment by bledbet** [comment]
Thanks for the response - I'll see where I can fit in an occasional disposal of the main Browser instance without impacting throughput too badly.

I appreciate this project - I tried a few other approaches to this problem set, and SimpleBrowser was by far the fastest at getting our particular workflows done with the least amount of transient browser problems.  Good work!

**Comment by kevingy** [comment]
Like most open source projects, SimpleBrowser is a group effort. While I will say "Thank you!" for the compliments, I am accepting them on behalf of all of the contributors and users like yourself who have improved the software since creation.

Let me know if I can be of further assistance.

**Comment by bledbet** [comment]
In case it is helpful, it looks like my approach will be to instantiate a fresh browser object for each "task", and at the end of the task, retain the CookieContainer for the logged-in application session, but dispose of the Browser, then on the next task, build a new Browser, set the CookieContainer, and perform the next task for that user.
