### ISSUE TITLE
HTTP Headers, Cookie, Proxy and HTTP status code

### ISSUE THREAD

**Issue by vickyrathee** [SimpleBrowserDotNet/SimpleBrowser#162]
Can i set custom HTTP headers, cookie using Simplebrowser, any example?
I need to set User-Agent, Referrer to web requests and public or password protected proxy sometime.

> **Password Protected Proxy** : http://username:password@123.11.32.122:8080
> **Public Proxy** : http://123.11.32.122:8080

Also, how to get the HTTP stauts code(200, 301, 401, 404 etc.) of requests sent through Simplebrowser?

**Comment by kevingy** [comment]
vickyrathee,

A little research goes a long way. The answers to all of your questions were either available in the wiki, samples, or easily discerned with a little code examination.

> Can i set custom HTTP headers

Yes, using the Browser.SetHeader() method:

```
Browser b = new Browser();
browser.SetHeader("host:uscloud.asldkfhjawoeif.com");
```
(Taken from HttpHeaderTests.cs.)

> cookie using Simplebrowser

Yes, by manipulating the Browser.Cookies property:

```
Browser b = new Browser();
b.Cookies.Add(new Cookie("bane", "value"));
```

> I need to set User-Agent

Yes, using the UserAgent property:

```
Browser b = new Browser();
b.UserAgent = "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10";
```
(Taken from the SimpleBrowser home page.)

> Referrer to web requests

Yes, using the Referer property:

```
Browser b = new Browser();
b.Referer = "http://www.yourreferer.com";
```

> public or password protected proxy

Yes, using the SetProxy() method:

```
IWebProxy proxy = new WebProxy("123.11.32.122", 8080);
proxy.Credentials = new NetworkCredential("username", "password");

Browser b = new Browser();
b.SetProxy(proxy);
```

> Also, how to get the HTTP stauts code(200, 301, 401, 404 etc.) of requests sent through Simplebrowser?

Yes, using the RequestData() method:

```
Browser b = new Browser();
b.Navigate("http://icanhazip.com");
Console.WriteLine(b.RequestData().ResponseCode);
```

**Comment by vickyrathee** [comment]
@kevingy  Thanks for the nice examples, it works and helped a lot!
