### ISSUE TITLE
HTTP Proxy and Cookie

### ISSUE THREAD

**Issue by vickyrathee** [SimpleBrowserDotNet/SimpleBrowser#163]
Can i set custom HTTP proxy and cookie using Simplebrowser, any example?
I need to set random proxy from my list for around 1000 URL web requests and some of the proxy are public and some are password protected.

> **Password Protected Proxy** : http://username:password@123.11.32.122:8080
> **Public Proxy** : http://123.11.32.122:8080

**Comment by kevingy** [comment]
Duplicate of the previous issue.
