### ISSUE TITLE
The HTTP ResponseCode for errored request is always 0

### ISSUE THREAD

**Issue by vickyrathee** [SimpleBrowserDotNet/SimpleBrowser#164]
```
var browser = new Browser();
            // attach event handler to look into the exact requests later
            browser.RequestLogged += new Action<Browser, HttpRequestLog>(HandleRequestLogged);
            string[] urlList = new string[3];
            urlList[0] = "http://www.pricetree.com/faq.aspx";
            urlList[1] = "http://www.pricetree.com/bad-page-url.aspx"; // Should return 404 not found
            urlList[2] = "http://www.pricetree.com/contact.aspx";            
            foreach (string url in urlList)
            {
                browser.Navigate(url);
            }
public static void HandleRequestLogged(Browser req, HttpRequestLog log)
        {
            Console.WriteLine(log.Url);
            Console.WriteLine(log.ResponseCode);
        }
```

![http-bad-error](https://cloud.githubusercontent.com/assets/6106479/13352565/1c5fbbaa-dcb4-11e5-86fa-24a5c6d52c6d.jpg)

**Comment by kevingy** [comment]
Checked in a fix. Please pull the latest code from the repository.

**Comment by vickyrathee** [comment]
Can you please also check in the latest on nuget and we will update our
package.

**Comment by Teun** [comment]
@kevingy Do you feel the current code base is good enough to publish? I see that we haven't published for quite a while, so it contains many more changes that just this fix.

**Comment by Teun** [comment]
Ah well. I guess most of those changes have been in master for months now. I'll just publish. :)

**Comment by Teun** [comment]
Version #0.5.79 published to nuget

**Comment by vickyrathee** [comment]
Seems something wrong or DLL not signed before publishing to nuget?

![dll-error](https://cloud.githubusercontent.com/assets/6106479/13372869/64a93788-dd7c-11e5-8126-cf9f44c324d7.JPG)

**Comment by Teun** [comment]
SimpleBrowser is not strong-named and never had been. Can you try to add the reference again?

**Comment by kevingy** [comment]
@Teun I think it's safe enough. My changes recently have been incrementally working up to a large change. Now is actually a very good time.

**Comment by vickyrathee** [comment]
@Teun Thanks re-installing did the trick, it's working now. Thanks again. I've one more problem will open a new thread :+1:
