### ISSUE TITLE
the last boundary separator not correct

### ISSUE THREAD

**Issue by luqw** [SimpleBrowserDotNet/SimpleBrowser#168]
[Issue]
I used wireshark  to get the http row data, and posted data with boundary had one error in wireshark:
--------------------------------------------
[Malformed Packet: MIME multipart]
    [Expert Info (Error/Malformed): Malformed Packet (Exception occurred)]
        [Malformed Packet (Exception occurred)]
        [Severity level: Error]
        [Group: Malformed]
----------------------------------------------

I analyzed the code, and HTTP protocol, and found that the reason is because the last boundary separator is not correct.
The last boundary separator should be like below "--boundary--".

--boundary
1. body-part
--boundary
2. body-part
--boundary
3. body-part
--boundary--

[solution]
SimpleBrowser\Elements\FormElement.cs#171
post.AppendFormat("--{0}\r\n", token);
->
post.AppendFormat("--{0}--\r\n", token);

**Comment by kevingy** [comment]
Thanks for the contribution. This has been fixed in the code base.
