### ISSUE TITLE
Method described in tutorial for working with malformed HTML won't work

### ISSUE THREAD

**Issue by kaspars-ozols** [SimpleBrowserDotNet/SimpleBrowser#173]
Method described in tutorial on how to fix malformed HTML won't work because `string.Replace` does not manipulate original string in any way. 

`b.CurrentHtml.Replace("badtoken", "goodtoken");`

It just returns a new string where value has been replaced. Would be great if it was possible to pass delegate or lambda to modify response before parsing.

**Comment by kevingy** [comment]
Good catch! It should be:

```
b.CurrentHtml = b.CurrentHtml.Replace("badtoken", "goodtoken");
```

Since Browser.CurrentHtml is a string property, you can use whatever string methods are available to set it's value before the first call to Browser.Find().

I have updated the wiki.

**Comment by kaspars-ozols** [comment]
Still not correct. CurrentHtml does not have setter.

**Comment by kevingy** [comment]
I'll have to check my code. I do this - or at least something like this - all the time.

**Comment by kevingy** [comment]
Searching all of my current scripts, it appears that I don't do this all the time. In fact, I don't do it at all. I used to.

I see code where I am doing DOM manipulation after parsing. If the parser is crashing on the content, that won't help. The setter on CurrentHtml must have been removed at some point. The next thing to do is check the revision history.

**Comment by kaspars-ozols** [comment]
In my case it did not crash, it just didn't work as expected. Currently I
worked around issue by manipulating XDocument elements. It ain't pretty as
XDocument is result of parsing.

I would suggest to add property where you can set delegate or lambda to
transform markup before parsing.

Func<string, string> TransformMarkup {get; set;}

Then you would just have to call it once when fetching markup from
CurrentState object..

**Comment by kevingy** [comment]
Determined and tested different method. Updated documentation with working method.
