### ISSUE TITLE
Form without action attribute

### ISSUE THREAD

**Issue by kaspars-ozols** [SimpleBrowserDotNet/SimpleBrowser#174]
Form without action attribute should be submitted to the current URL. In current implementation it is submitted to base URL.

Example:

Lets say I have form located at URL "mydomain.com/login"

```
<form method="post" novalidate="novalidate">
   
            <button class="btn btn-theme">
                Log In
            </button>
        </div>
        <div class="clearfix"></div>
    </div>
</form>
```

In current implementation it submits form to "mydomain.com". It should post to "mydomain.com/login" instead.

**Comment by kevingy** [comment]
Checked in a fix for this. The broken behavior has been there for at least 4 years, according to the revision history. Good find.
