### ISSUE TITLE
Extension / Add ons

### ISSUE THREAD

**Issue by icatchinfosec** [SimpleBrowserDotNet/SimpleBrowser#178]
Can I add my own extension which I was using for mozilla?

**Comment by kevingy** [comment]
We currently do not have the infrastructure in place to offer the ability to add plug-ins or extensions to SimpleBrowser. Any addition you might make would have to be added directly to the code base at this time.

What does the extension do? Is it something that others might benefit from?

**Comment by kevingy** [comment]
No reply in 15+ days. Closing. If you need further assistance, reopen the issue and reply. Thanks!
