### ISSUE TITLE
HTTP Post after logged in

### ISSUE THREAD

**Issue by vickyrathee** [SimpleBrowserDotNet/SimpleBrowser#181]
I'm using SimpleBrowser webdriver with selenium. 

I need to login to site and then submit HTTP POST request and then read the response, I noticed below given method in browser. But couldn't find way hot to use?

public bool Navigate(Uri url, string postData, string contentType);
public bool Navigate(Uri url, NameValueCollection postData, string contentType = null, string encodingType = null);

I can see this below one only working with HTTP GET.  Any thought?
browser.Navigate().GoToUrl(url);

**Comment by kevingy** [comment]
@Teun  is the WebDriver expert, but I can talk to SimpleBrowser. A http post in a web browser is typically performed by submitting a form. Typically, one would fill the login form with a username and password then click a submit button. In SimpleBrowser, these actions are all performed individually. For example, this pseudocode:

```
var browser = new SimpleBrowser();
browser.Navigate("http://yoururl.com");
var username = browser.Find("username");
username.Value = "user";
var password = browser.Find("password");
password.Value = "password";
var submit = brwoser.Find("submit");
submit.Click();
```

For more information, see the Wiki:
https://github.com/SimpleBrowserDotNet/SimpleBrowser/wiki/Tutorial#submitting-forms

Please let me know how that works for you.

**Comment by vickyrathee** [comment]
@kevingy Thanks, this is helpful. I just need to login capability so can work with the simplebrowser as well (no need of webdriver) :+1: 

Any plan to implement JavaScript as well? it's needed for many website login these days. I know that will make the simplebrowser slow but can have enable/disable option to use only when it's really in need.

**Comment by kevingy** [comment]
There is no plan to implement JavaScript in SimpleBrowser. It's not a question of speed. The current SimpleBrowser architecture doesn't support it. We'd basically have to rewrite everything. It's too big an effort.
