### ISSUE TITLE
Exception-The requested operation is not available. Navigating makes the existing HtmlResult objects invalid.

### ISSUE THREAD

**Issue by niri123** [SimpleBrowserDotNet/SimpleBrowser#182]
Navigating to this url
   browser.Navigate("https://www.sprintax.com/log-in.html");
  browser.Find("user_name").Value = "xxxxxxxx@gmail.com";
                browser.Find("password").Value = "xxxxxxxxx";
 if (!signInLink.Exists)
                    browser.Log("Can't find the singin link! Perhaps the site is down for maintenance?");
                else
                {
                    signInLink.Click();//there is an exception at this line-The requested operation is not available. Navigating makes the existing HtmlResult objects invalid.
}
I am a new bee and i need to login to a site and then perform some task . Please let me how to resolve this issue.

**Comment by kevingy** [comment]
I don't think this is all of the code. This will not compile.

1. You are using signInLink, but it's not declared or assigned anywhere.
2. There has to be an action between browser.Find() and signInLink.Click() that's changing the navigation state.

The exception is probably correct, but without all of the code, I can't tell you why or how to fix it. I need more code.

**Comment by niri123** [comment]
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using SimpleBrowser;
using SimpleBrowser.Parser;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            var browser = new Browser();
            try
            {
                // log the browser request/response data to files so we can interrogate them in case of an issue with our scraping
                browser.RequestLogged += OnBrowserRequestLogged;
                browser.MessageLogged += new Action<Browser, string>(OnBrowserMessageLogged);

                browser.UserAgent = "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10";

                // browse to GitHub
                browser.Navigate("https://www.sprintax.com");
                if (LastRequestFailed(browser)) return; // always check the last request in case the page failed to load

                var signInLink = browser.Find("input", FindBy.Id, "button_subscribe");

                browser.Find("user_name").Value = "testsoftware03@gmail.com";
                browser.Find("sign_in_password").Value = "catchmeifucan12";

                if (!signInLink.Exists)
                    browser.Log("Can't find the singin link! Perhaps the site is down for maintenance?");
                else
                {
                    signInLink.Click();
                    if (LastRequestFailed(browser)) return;
                    if (browser.Find("leftbar").Value == "You are here")
                    {
                        browser.Log("Success");
                        var sigoutLink = browser.Find("a", FindBy.Text, "Log out");
                        if (sigoutLink.Exists)
                        {
                            sigoutLink.Click();
                        }
                    }
                   
                }
            }
            catch (Exception ex)
            {
                browser.Log(ex.Message, LogMessageType.Error);
                browser.Log(ex.StackTrace, LogMessageType.StackTrace);
            }
            finally
            {
                var path = WriteFile("log-" + DateTime.UtcNow.Ticks + ".html", browser.RenderHtmlLogFile("SimpleBrowser Sample - Request Log"));
                Process.Start(path);
            }
        }

        static bool LastRequestFailed(Browser browser)
        {
            if (browser.LastWebException != null)
            {
                browser.Log("There was an error loading the page: " + browser.LastWebException.Message);
                return true;
            }
            return false;
        }

        static void OnBrowserMessageLogged(Browser browser, string log)
        {
            Console.WriteLine(log);
        }

        static void OnBrowserRequestLogged(Browser req, HttpRequestLog log)
        {
            Console.WriteLine(" -> " + log.Method + " request to " + log.Url);
            Console.WriteLine(" <- Response status code: " + log.ResponseCode);
        }

        static string WriteFile(string filename, string text)
        {
            var dir = new DirectoryInfo(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Logs"));
            if (!dir.Exists) dir.Create();
            var path = Path.Combine(dir.FullName, filename);
            File.WriteAllText(path, text);
            return path;
        }
    }
}
Here is my code

**Comment by kevingy** [comment]
The problem is here:
```
signInLink.Click();
if (LastRequestFailed(browser)) return;
if (browser.Find("leftbar").Value == "You are here")
```
You are filling in the sign in form and submitting the form. After submitting the form, the resulting page does not contain a _leftbar_ Therefore browser.Find("leftbar").Value is invalid, throwing an appropriate exception. This is more correct:

```
signInLink.Click();
if (LastRequestFailed(browser)) return;
var element = browser.Find("leftbar");
if (element.Exists && element.Value == "You are here")
```
Always check for existence of an element before attempting to use it. That takes care of the exception. As for why there's no _leftbar_, when I run your code the resulting page doesn't have one. That may be because you changed the username and password before sending me the code. (I would have too, if I were you.) In the resulting page, I see "Login failed! Please try again."

Good luck!

**Comment by kevingy** [comment]
@niri123 I haven't heard from you in 5 days. I'm going to consider this issue closed. If you need further assistance, this issue can be re-opened.

**Comment by niri123** [comment]
HI 
Please re-open the issue the problem is here is with sigbIn.Click() ....please find below which i created for testing 
I am trying to click the signInlink and its in the same page thats why i am not able to the var element = browser.Find("leftbar");


Below is the new code
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using SimpleBrowser;
using SimpleBrowser.Parser;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            var browser = new Browser();
            try
            {
                // log the browser request/response data to files so we can interrogate them in case of an issue with our scraping
                browser.RequestLogged += OnBrowserRequestLogged;
                browser.MessageLogged += new Action<Browser, string>(OnBrowserMessageLogged);

                browser.UserAgent = "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10";

                // browse to GitHub
                browser.Navigate("https://www.sprintax.com/log-in.html");
                if (LastRequestFailed(browser)) return; // always check the last request in case the page failed to load

                var signInLink = browser.Find("input", FindBy.Id, "button_subscribe");

                browser.Find("user_name").Value = "testsoftware03@gmail.com";
                browser.Find("password").Value = "test1234";

                if (!signInLink.Exists)
                    browser.Log("Can't find the singin link! Perhaps the site is down for maintenance?");
                else
                {
                    signInLink.Click();
                    if (LastRequestFailed(browser)) return;
                   signInLink.Click();
if (LastRequestFailed(browser)) return;
var element = browser.Find("leftbar");
if (element.Exists && element.Value == "You are here"){  browser.Log("Success");}
                   
                }
            }
            catch (Exception ex)
            {
                browser.Log(ex.Message, LogMessageType.Error);
                browser.Log(ex.StackTrace, LogMessageType.StackTrace);
            }
            finally
            {
                var path = WriteFile("log-" + DateTime.UtcNow.Ticks + ".html", browser.RenderHtmlLogFile("SimpleBrowser Sample - Request Log"));
                Process.Start(path);
            }
        }

        static bool LastRequestFailed(Browser browser)
        {
            if (browser.LastWebException != null)
            {
                browser.Log("There was an error loading the page: " + browser.LastWebException.Message);
                return true;
            }
            return false;
        }

        static void OnBrowserMessageLogged(Browser browser, string log)
        {
            Console.WriteLine(log);
        }

        static void OnBrowserRequestLogged(Browser req, HttpRequestLog log)
        {
            Console.WriteLine(@" -> {0} request to {1}", log.Method, log.Url);
            Console.WriteLine(@" <- Response status code: {0}", log.ResponseCode);
        }

        static string WriteFile(string filename, string text)
        {
            var dir = new DirectoryInfo(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Logs"));
            if (!dir.Exists) dir.Create();
            var path = Path.Combine(dir.FullName, filename);
            File.WriteAllText(path, text);
            return path;
        }
    }
}

**Comment by kevingy** [comment]
> Please re-open the issue... the problem here is with the signIn.Click() ....please find below credentials which i created for testing

Before I go any further, let's make sure we're completely clear on one thing. My role here is to support SimpleBrowser. I'm not going to re-open the issue, because there isn't an issue with SimpleBrowser. The problem here is _your broken code_.

That said, I'm more than willing to help you, but you really have to understand the basic operation of the software. For starters this will simply not work - ever:
``` c#
signInLink.Click();
if (LastRequestFailed(browser)) return;
signInLink.Click();
```

The first signInLink.Click() will change the navigation state of the browser, invalidating signInLink. The second call to signInLink.Click() will fail every time.

> I am trying to click the signInlink and its in the same page that's why i am not able to see the var element = browser.Find("leftbar"); which mean the click is never happening . Please check below code and suggest me.

I've confirmed both by tracing through SimpleBrowser and using Fiddler. The click is indeed happening. In fact, the form content posted to the web server is:

`doit=1&reg_timestamp=20170303035844&reg_signature=baa4df203e288ae1d860ed186971d839ecd7d046&form_id=14_1&uid_order=5ee865072efb046d199e4d2cd5cde97fab27125a&step=1&user_name=testsoftware03%40gmail.com&sign_in_password=&button_subscribe=login`

If you'll notice, the value of _sign_in_password_ is empty string. Looking back at your code, you are populating the wrong form element. This line:
``` c#
browser.Find("password").Value = "test1234";
```
should be:
``` c#
browser.Find("sign_in_password").Value = "test1234";
```

This results in the following response from the server:
![image](https://cloud.githubusercontent.com/assets/411556/23535410/32e1753e-ff8c-11e6-8942-38ea93cd0e29.png)
That is, a redirect to the visa-program.html page, following a successful login.

**Comment by niri123** [comment]
HI ,
i am sorry ..I am confused here how to take the id of the control when i see the if for password text box throughsource code its "password" but as i changed the id given by you it worked...
Can you please let me know for the below link what will be the email address and password fields
https://www.flashseats.com/Default.aspx?pid=25&ss=0
Right now i am trying to set the value with these Id's but the login is not successful though the credentials are correct. Kindly let me know
Thanks in advance
 browser.Find("ctl00_ctl02_Email").Value = "xxxxxxxxxxxx"
                browser.Find("ctl00_ctl02_Password").Value ="xxxxxxx"

**Comment by kevingy** [comment]
ctl00_ctl02_Email and ctl00_ctl02_Password are the correct values to use. When performing a Find with one parameter, the Find always looks for the id attribute.

Looking at flashseats,com, this site uses a tremendous about of JavaScript. That being the case, it may not be possible to easily access using SimpleBrowser.
