### ISSUE TITLE
How to pass NetworkCredential with SimpleBrowser

### ISSUE THREAD

**Issue by vickyrathee** [SimpleBrowserDotNet/SimpleBrowser#183]
I have a site which uses the www-authentication and the BasicAuthenciation didn't works there. But I checked that NetworkCredential  works using WebClient. Is there any way I can pass NetworkCredential  to browser?

**Comment by kevingy** [comment]
The short answer is no. There is currently no way to pass a NetworkCredential instance into SimpleBrowser. One can be created, however.

That said, I don't understand what you're trying to accomplish. The WWW-Authenticate HTTP header _is_ BasicAuthentication. I find it odd that WWW-Authenticate works with NetworkCredential and WebClient, but not BasicAuthentication. Have you used a network traffic sniffing tool like Fiddler to see if there is a difference in the HTTP headers sent by SimpleBrowser and WebClient? It could be that SimpleBrowser BasicAuthentication has a bug in it that needs to be fixed.

**Comment by vickyrathee** [comment]
Yes @kevingy . I checked with fiddler and looks like a bug, the BasicAuthenticationLogin method not sending any http/https request to domain to login. I tried several time with different domains and nothing got recorded in fiddler for this BasicAuthenticationLogin  method while the other request like navigate etc recorded correctly.

**Comment by kevingy** [comment]
I just tested with Fiddler. When the call is made from Chrome or from SimpleBrowser, I'm seeing the same response:
![image](https://user-images.githubusercontent.com/411556/27545797-c9b5c4b0-5a5e-11e7-9afb-dc8db427aeff.png)
The requests look different, which is expected. SimpleBrowser isn't as complicated as Chrome:
SimpleBrowser request:
![image](https://user-images.githubusercontent.com/411556/27546402-a9a10624-5a60-11e7-82d9-325d3c91c0ad.png)
Chrome request:
![image](https://user-images.githubusercontent.com/411556/27546434-bee61f10-5a60-11e7-88c0-af5478076550.png)

SimpleBrowser looks like it's working correctly.

Are you using SimpleBrowser BasicAuthentication correctly? In Chrome, a request is made to the server. The server responds with a 401 Unauthorized and WWW-Authenticate: Basic realm="_domain_". Chrome then pops up a login dialog. If you enter a username and password and click OK, Chrome re-submits the original request with an Authorization header. If the authorization is correct, the web server serves content. If not, you get a 401 Unauthorized again.

In SimpleBrowser, there is no UI. Therefore, there is no user interaction loop. Before calling a site that is protected by BasicAuthentication, you need to have the authentication already preconfigured. Have you read the SimpleBrowser Wiki on BasicAuthentication?

https://github.com/SimpleBrowserDotNet/SimpleBrowser/wiki/Tutorial#basic-authentication

Is the site that you are attempting to access a public site? Can I get access to it to further help debugging?)

**Comment by vickyrathee** [comment]
I found the issue. When I use the full url in BasicAuthenticationLogin domain that fails, but using the domain works 

**This errors**
```
browser.BasicAuthenticationLogin(
                    "http://api.domain.com/product/12", 
                    "username", 
                    "password"
                );
```

**This works**

```
browser.BasicAuthenticationLogin(
                    "api.domain.com", 
                    "username", 
                    "password"
                );
```

So I think I need to extract the domain from client provided url to authenticate with domain first, then navigate to that full url. But technically this should be handled by SimpleBrowser I think and should attempt to login on whatever the url/domain is provided?

**Comment by kevingy** [comment]
@vickyrathee,

Your "This works" example is what it should be. Basic Authentication protects the entire realm (domain), not a specific page.

The way basic authentication works (in all browsers, not just SimpleBrowser) is the user authenticates once. The browser creates and stores a basic authentication token that is used for future calls to the domain protected by basic authentication. By default, the token expires after 15 minutes of inactivity. That is, as long as you make at least one call every 15 minutes, the token will never expire. The browser can also delete the token (to log out).

It looks like SimpleBrowser is working correctly.
