### ISSUE TITLE
</script > close tag not parsed correctly

### ISSUE THREAD

**Issue by twpol** [SimpleBrowserDotNet/SimpleBrowser#186]
When parsing real-world HTML that contains a script tag in the form (note the space before the ">"):

    <script>
    </script >

SimpleBrowser fails to spot this close tag and consumes the remaining HTML as part of the script. The issue is likely from this regular expression:

https://github.com/SimpleBrowserDotNet/SimpleBrowser/blob/08649130b921f976b21f16cab67ade24a79bd991/SimpleBrowser/Parser/HtmlTokenizer.cs#L46

**Comment by kevingy** [comment]
James,

You are correct, this is a problem with the parser and, more specifically, the regular expression you indicate. The HTML5 specification clearly states:

```
8.1.2.2 End tags

End tags must have the following format:

1. The first character of an end tag must be a "<" (U+003C) character.
2. The second character of an end tag must be a "/" (U+002F) character.
3. The next few characters of an end tag must be the element's tag name.
4. After the tag name, there may be one or more space characters.
5. Finally, end tags must be closed by a ">" (U+003E) character.
```
The regular expression is clearly missing item 4.

Thanks for reporting this issue. I'll fix it as soon as I can.

Kevin

**Comment by kevingy** [comment]
@twpol 

I had some clean-up work to do on the unit tests before I could proceed with the fix. Both the work on the unit tests and the fix for this bug have been committed.

I'm going to close this issue. If the fix doesn't work for you (although it worked in my testing and unit tests), let me know.

Kevin
