### ISSUE TITLE
Update to VS2017 / new csproj format

### ISSUE THREAD

**Issue by Styxxy** [SimpleBrowserDotNet/SimpleBrowser#188]
Hi,

I am currently upgrading the solution to VS2017 and changing the projects to the new CSPROJ file format. This new format will be needed to add support for .NET Standard (see #189 ).

Is this okay for you?

Kind regards,
Styxxy

**Comment by kevingy** [comment]
Yes, please. I had entered a task to update to Visual Studio 2015, but never got to it. At this point, it's better to upgrade to 2017.

**Comment by Styxxy** [comment]
I finished the csproj conversion however need to finish up a few things (like the nuspec).

You do a manual build and version update for releasing a nuget package, right?

I noticed also a few unit test failing, however this was also the case in the original source (before converting the project files). I won't change or fis them with this issue. I'll open another issue for that later.

PR is coming soon.

**Comment by kevingy** [comment]
I fixed the unit tests yesterday. A couple external dependencies either changed or were 404, breaking the tests. You probably won't have those changes in your fork.

Honestly, I don't know how we do Nuget releases. I haven't created one. I was getting set up to do them, but got busy with other things. I need to learn that process.

**Comment by Styxxy** [comment]
Waiting for the PR to be approved and merged :-).

**Comment by kevingy** [comment]
FYI: I'm looking at this pull request today. I'm sorry for the delay.

**Comment by kevingy** [comment]
Pull request merged. Thank you for your help to improve SimpleBrowser!
