### ISSUE TITLE
new Browser in Assisted mode.

### ISSUE THREAD

**Issue by fbuckeri** [SimpleBrowserDotNet/SimpleBrowser#192]
368/5000
I searched the internet and here, but I do not know if I'm looking for the wrong term.
I'm unfortunately not able to run the new SimpleBrowser so that I can see the interaction being made on the page.

I do not know how to speak English fluently. Sorry for my language errors.

Is there a way to run the tests so you can see the interaction?

**Comment by Teun** [comment]
No, that is not possible. SimpleBrowser does not have a UI. It is made to
be invisible (this is called Headless). If you want to automate a browser
that you can see, you may want to look into automating normal browsers like
Chrome or FireFox using Selenium WebDriver (
http://www.seleniumhq.org/projects/webdriver/).

2018-01-17 18:14 GMT+01:00 fbuckeri <notifications@github.com>:

**Comment by fbuckeri** [comment]
I understood, actually I already imagined that.

Today I use Selenium, but I need the interaction to be hidden, just like the SimpleBrowser.

I'm trying to migrate, but I'm encountering some difficulties.

Is there any forum that I can put my doubts to help? Can I post it right here?

I believe they are simple doubts, but that I could not solve. For example, in one of the links opens a new tab. I can not access this new tab to sequence the process.

In debug mode, it does not appear, but in Selenium it is perfect.

Thank you again for taking my question. And I await a return on where I can post my doubts.
