### ISSUE TITLE
Browsing to http://developermedia.com/ causes exception

### ISSUE THREAD

**Issue by Styxxy** [SimpleBrowserDotNet/SimpleBrowser#196]
Browsing to causes an exception (underlying connection is closed).

When testing .NET Standard and .NET Core (see issue #189 ), it actually works on .NET Core, but not on .NET Full.

```cs
var browser = new Browser();
var success = b.Navigate("http://developermedia.com/");
// success == false
// see browser.LastWebException
```

**Comment by kevingy** [comment]
As of 20 July 2018, the unit tests are running without exception. Since we currently rely on public URLs for some online testing, this may be a temporary situation. I'm going to close this issue. If the test start failing again, we can re-open it.
