### ISSUE TITLE
Is it Possible to Make a HTTP Post Request?

### ISSUE THREAD

**Issue by takielias** [SimpleBrowserDotNet/SimpleBrowser#201]
**https://pastebin.com/QGqchKTR** This the HTTP Post request Data that is performed by Firefox.  
So, Is it possible to Make a HTTP post request where HTML form does not exist?

**Comment by kevingy** [comment]
Yes. The entire HTML form can be injected into the page. After that is done, you can submit the form. The tutorial at https://github.com/SimpleBrowserDotNet/SimpleBrowser/wiki/Tutorial has an example of how to do this for one field. Use that as a template to expand to create the entire form.

**Comment by kevingy** [comment]
No reply from @takielias in a few days. I'm going to assume the problem has been resolved.

**Comment by kevingy** [comment]
Closing.

**Comment by kevingy** [comment]
Still trying to close. Github isn't cooperating.

**Comment by takielias** [comment]
Got it. Thanks.
