### ISSUE TITLE
Supress javascript errors

### ISSUE THREAD

**Issue by acosonic** [SimpleBrowserDotNet/SimpleBrowser#219]
I keep having javascript error popups, 

there is no 

browser.ScriptErrorsSuppressed = true;

property anymore.

Any ideas?

**Comment by kevingy** [comment]
SimpleBrowser doesn't have a UI and doesn't run JavaScript. I don't understand how you could have JavaScript error popups. Can you send a screen capture of what you are seeing?

I don't remember ever having a ScriptErrorsSuppressed property.

**Comment by acosonic** [comment]
![image](https://user-images.githubusercontent.com/862015/53173128-53228700-35e7-11e9-9f7c-8cc1fe6fb56d.png)

**Comment by kevingy** [comment]
This appears to be a problem with Visual Studio and IE, not SimpleBrowser. Please try the solution described in this link and see if it fixes your problem:

https://developercommunity.visualstudio.com/content/problem/218740/vs2017-debug-javascript-files-not-working-1.html

**Comment by kevingy** [comment]
@acosonic Did this address your issie?

**Comment by kevingy** [comment]
I believe this to be a Visual Studio/IE error, not a SimpleBrowser error. The OP hasn't replied. I'm going to close this issue until there is a reason to have it open.
