### ISSUE TITLE
How to automate download excel or csv file, and set directory

### ISSUE THREAD

**Issue by mach37** [SimpleBrowserDotNet/SimpleBrowser#225]
Hello, is there a sample on how to 

1. Navigate a page
2. Then Download a file, with a date appended to name
3. Set a target folder

**Comment by kevingy** [comment]
The ability to download a file to disk is currently in development. It is not currently possible.

Another SimpleBrowser user has submitted a way to do this in issue #37. You can try that solution, but that will not be the eventual SimpleBrowser implementation. I suggest looking at issue #37 for now.

I'm closing this issue as a duplicate.
