### ISSUE TITLE
Html Loaded by script

### ISSUE THREAD

**Issue by AlenToma** [SimpleBrowserDotNet/SimpleBrowser#227]
I tested your library and its really a greet library.

Im having a small issue and i dont know if the library is able to complete the task or its just me who dont know how it really work.

Im loading this url 
`https://keepvid.pro/download?video=OOCpdwZ74WE`
It work find except, there is some html thats load by javascript(Ajax), and those html simple do now show up when using simplebrowser.

Do i need to enable somthing?

**Comment by kevingy** [comment]
Hi @AlenToma 

SimpleBrowser does not support JavsScript. The short answer is that SimpleBrowser will not do what you need - at least not without additional help.

Depending on how the site is coded and your requirements, there might be something that you can do to get around this. Are you able to parse out the link that is called via JavaScript? If so, you might be able to call that link manually via SimpleBrowser. Again, it really depends on the site you are accessing and your requirements.

Can you share the URL of the site you are trying to access? I'm not sure how much more I can help without more information on the problem.

Kevin

**Comment by AlenToma** [comment]
Here is the url 
`https://keepvid.pro/download?video=OOCpdwZ74WE`

The web site restrict ajax call that are out side of thair orgin, so doing it will only give access denied.

The only solution is that i wait for the ajax to load the html and then retrive the html.
Which leads me to Webbrowser controller, but it still not possiable for me as im using netstandard 2.0.

I solved the problem by building a library that dose what the web site do, as that was the only solution for me. 

Thx for the support anyway.

**Comment by kevingy** [comment]
You are welcome.

That being the case, I'll close this issue.
