### ISSUE TITLE
SSL issue when navigating

### ISSUE THREAD

**Issue by SeyoS** [SimpleBrowserDotNet/SimpleBrowser#228]
When navigating to a some https page (like 'https://www.hellobank.fr/), i got the error 'The request has been abandoned: Unable to create a secure SSL/TLS channel' (sorry for the translation).

I tried to use `ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;` with no success.

Is there a way to go through an SSL error ?

**Comment by kevingy** [comment]
Are you using the code from the repository or the Nupet package? The Nuget package is significantly older than the repo. Are you using .NET Framework or .NET Core?

There was an SSL issue that was fixed in the .NET Framework version of the library. This fix is not in the Nuget repository.

**Comment by SeyoS** [comment]
I'll try with the repo and i'll tell you.
I'm using .NET Framework.

**Comment by SeyoS** [comment]
Thanks, the repository version worked fine even if it seems that it don't find anything using the `browser.Find('tag')` command. I certainly miss something.
