### ISSUE TITLE
Click on HTML element

### ISSUE THREAD

**Issue by SeyoS** [SimpleBrowserDotNet/SimpleBrowser#229]
It seems that the click on a HtmlElement (like `div` or `li`) is not working.
Is it implemented ? Is there a way to simulate it via JavaScript injection ?

**Comment by kevingy** [comment]
> It seems that the click on a HtmlElement (like div or li) is not working.
> Is it implemented ?

No. SimpleBrowser does not support JavaScript. Without JavaScript, div and li do not have click handler functions. In HTML, div and li are not clickable elements.

> Is there a way to simulate it via JavaScript injection ?

Yes. Whatever the JavaScipt does, you will have to do manually. Without knowing exactly what the JavaScript does, it's impossible to know for sure. Some of the common tasks performed by JavaScript are modifying the DOM and form submission - both of which are possible with SimpleBrowser.

**Comment by kevingy** [comment]
@SeyoS Do you need further assistance with this issue? If so, I'm happy to help by looking at the JavaScript that you are working with. If not, since this isn't a problem with SimpleBrowser, I'll close the issue.

**Comment by SeyoS** [comment]
Sorry for the delay.
It's a rather big script so I'll try something else.

Thanks!
