### ISSUE TITLE
Need some code samples for JS counterpart: getElementsByClassName

### ISSUE THREAD

**Issue by johngit2020** [SimpleBrowserDotNet/SimpleBrowser#245]
Hello:
I have a new project which needs to extract some dynamic text from a web site, but I don’t need image or other things.   I found SimpleBrowser seems to be a good tools to do my job, as my program language is C# on Windows 10.
However, I can’t find enough examples and/or tutorial to continue my project.  The biggest issue is: I don’t know how to do the task as in JavaScript: getElementsByClassName.
I created the following simple HTML on my local PC: http://localhost/TestClass.html 
With the following HTML contents:

![TestClassHtml](https://user-images.githubusercontent.com/59543428/71787844-ce810180-301c-11ea-9671-ecdae58fc6af.jpg)

If I open Chrome browser and visit:  http://localhost/TestClass.html
And in developer tools, I can use this JavaScript command to get some HTML elements:
var titles = document.getElementsByClassName('title');
However, when I use SimpleBrowser, I can navigate to http://localhost/TestClass.html
And see the CurrentHtml, it works well.
But how I can use SimpleBrowser to get variable as I did with JavaScript:
var titles = document.getElementsByClassName('title')
Please advice.
Thanks,

**Comment by kevingy** [comment]
@johngit2020 

There are some code samples at:
https://github.com/SimpleBrowserDotNet/SimpleBrowser/wiki/Tutorial

To your specific request, you can find elements by class name using the Browser.Select() method. I haven't used it much, but I think it's something like this:

`var titles = b.Select("span[@class='title']");`

or the Browser.Find() method, which I've used most:

`var titles = browser.Find("span", FindBy.Class, "title");`

That should do what you need.

Kevin

**Comment by johngit2020** [comment]
Hello:
Thanks, your code works.
But I want to know how to display HTML code here, as you can see I upload a picture in order to show the HTML code, since I can't figure out how to display HTML code here.
Please advice!

**Comment by kevingy** [comment]
https://guides.github.com/features/mastering-markdown/
