### ISSUE TITLE
How to use SimpleBrowser to click web links with some conditions

### ISSUE THREAD

**Issue by johngit2020** [SimpleBrowserDotNet/SimpleBrowser#246]
Hello:
I need to use SimpleBrowser to click on some web links without “https://www”; but I can’t figure this out, as without the https://www leading, the web links are not complete, so how I can click on those in-complete links?
I have some code like this: C# in Visual Studio 2019 (Windows 10).
    static async Task Main()
    {
        var sb = new Browser;
        sb.Navigate("https://www.google.co.uk/");
        HtmlResult urls = sb.Find("a", new object { });
        foreach (HtmlResult url1 in urls)
        {
        string link1 = url1.GetAttribute("href");
        if (!link1.Contains("https://www"))
        {
        }
   }
I can see some links in Google page don’t have https://www; for example:
"/preferences?hl=en"; "/advanced_search?hl=en&authuser=0"; and this one: "/intl/en/ads/"
But using Google Chrome, if there is any web link, you can simply click it and you can browse the web link even if its web link is not complete.
Please advice, how I can do the same, for example, visit the above 3 in-complete web links using SimpleBrowser using web link click.
Thanks,

**Comment by kevingy** [comment]
Browser.HtmlElement_NavigationRequested() converts the relative URL into an absolute URL, but you don't need to worry about that. Just like Chrome or any other browser, just click the link. I think you're over-complicating the problem. Your code could do something like this:

```sb.Navigate("https://www.google.co.uk/");
HtmlResult urls = sb.Find("a", new object { });
foreach (HtmlResult url1 in urls)
{
    url1.Click();
}
```

Of course, after clicking the first link, the other links are invalid. Are you trying to spider or use a browser?

**Comment by kevingy** [comment]
@johngit2020 Did that resolve your issue?

**Comment by kevingy** [comment]
No response from the original poster in a week. I'm going to assume the issue is resolved. If not, the issue can be re-opened.
