### ISSUE TITLE
How to find URL being visted

### ISSUE THREAD

**Issue by zydjohnHotmail** [SimpleBrowserDotNet/SimpleBrowser#247]
Hello:
I want to know if I can use SimpleBrowser to find which URL is called by clicking on some DOM element.
Some DOM elements use UUID or dynmaic ID to make URL being call.
The following is just a very simple link, in real world, the example is way more complicated than this.
``````
<script>
function uuidv4() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}
</script>
<p>Visit this link <span style="color:blue">https://www.test.com/uuidv4()</span></p>
``````
I want to know if I can use SimpleBrowser to click the DOM element with dynamic ID (UUID), but find out which URL is being visited?
Thanks,

**Comment by kevingy** [comment]
No. SimpleBrowser does not support JavaScript. In the context of SimpleBrowser, one can not click on a DOM element.
