### ISSUE TITLE
How to locate a textarea with no atributes

### ISSUE THREAD

**Issue by YouTrade** [SimpleBrowserDotNet/SimpleBrowser#252]
Can someone please help me find the right syntax to find and populate this text area that has no attributes?

![image](https://user-images.githubusercontent.com/26312941/80859944-d7848700-8c3a-11ea-89b3-1e49b1444812.png)

**Comment by kevingy** [comment]
@YouTrade I don't understand your question entirely. The highlighted text area does have attributes, namely `rows` and `style`. Using those, you can do any of the following:

```
Browser browser = new Browser();
HtmlResult result = null;
result = browser.Find("textarea", new { rows = "1" });
result = browser.Find("textarea", new { style = "height: 54px;" });
result = browser.Find(ElementType.TextField, new { rows = "1" });
result = browser.Find(ElementType.TextField, new { style = "height: 54px;" });
result = browser.Find(ElementType.TextField, "rows", "1");
result = browser.Find(ElementType.TextField, "style", "height: 54px;");
```

The result variable should hold the textarea.

If you don't want to use the `rows` or `style` attributes, you can always use an XPath select:

```
result = browser.Select("//div[contains(@class, 'fileWrapper ico')]/textarea");
```

Kevin

**Comment by YouTrade** [comment]
Dear Kevin

Thank you

One more question please ... how to populate this textarea in order to send information written inside this.

Best Regards

Marcelo

Sent from my YouTrade iPhone

**Comment by kevingy** [comment]
@YouTrade 

It should be as simple as setting the `Value` property:

```
Browser browser = new Browser();
HtmlResult result = browser.Find("textarea", new { rows = "1" });
if(result.Exists)
{
   result.Value = "some text";
}
```

**Comment by YouTrade** [comment]
Thank you very much. Please accept my apologies for the simple question. 

Sent from my YouTrade iPhone

**Comment by YouTrade** [comment]
One more question please.
What is the difference between these 2 ?

result = browser.Find(ElementType.TextField, new { style = "height: 54px;" });
result = browser.Find(ElementType.TextField, "style", "height: 54px;");

Thank you again please

**Comment by kevingy** [comment]
@YouTrade In most cases, there is no difference. I would have to look a the code, but many of the methods rework the parameters to call the same Find method.

Sometimes, bad HTML can cause the parser will generate unexpected XDocuments. Sometimes different find methods are needed to get to the HtmlResult desired.

**Comment by YouTrade** [comment]
Thank you very much. 

Keep you posted.

Obrigado 

Em 2020-05-02 13:59, Kevin Yochum escreveu:

> @YouTrade [1] In most cases, there is no difference. I would have to look a the code, but many of the methods rework the parameters to call the same Find method. 
> 
> Sometimes, bad HTML can cause the parser will generate unexpected XDocuments. Sometimes different find methods are needed to get to the HtmlResult desired. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/YouTrade
[2]
https://github.com/SimpleBrowserDotNet/SimpleBrowser/issues/252#issuecomment-622983470
[3]
