### ISSUE TITLE
Is it possible to download Image/File?

### ISSUE THREAD

**Issue by takielias** [SimpleBrowserDotNet/SimpleBrowser#254]
Hi, is there any way to download images/files and save on local computer using SimpleBrowser?

**Comment by kevingy** [comment]
@takielias I think this is SimpleBrower's longest requested, yet incomplete feature. Unfortunately, SimpleBrowser does not yet have the capability to download binary files. I worked on adding this feature months ago after the transition to .NET Standard but have not finished it yet.

**Comment by takielias** [comment]
I'm eagerly waiting to get this missing feature.
