### ISSUE TITLE
System.IO.FileNotFoundException in SimpleBrowser.dll

### ISSUE THREAD

**Issue by takielias** [SimpleBrowserDotNet/SimpleBrowser#255]
I cloned the project and made a reference to it. Everything is fine except browser.RenderHtmlLogFile("SimpleBrowser Sample - Request Log"). I'm getting this Exception thrown: 'System.IO.FileNotFoundException' in SimpleBrowser.dll

**Comment by kevingy** [comment]
@takielias Can you give me more information? I'm not seeing this issue. Do you have the full stack trace?

**Comment by kevingy** [comment]
No response from reporter. Closing.
