### ISSUE TITLE
How to set certificate (.cer .key) file in Simple Browser?

### ISSUE THREAD

**Issue by villar35738** [SimpleBrowserDotNet/SimpleBrowser#258]

**Comment by kevingy** [comment]
I don't know that you can. It looks like .NET (and therefore SimpleBrowser) only supports .pem files. If you can convert your .cer/.key to a .pem, use the Browser.SetCertificate method.

**Comment by villar35738** [comment]
I've used X509CertificateCollection and it works. Thanks!
