### ISSUE TITLE
Is there a way to SwitchTo another Window?

### ISSUE THREAD

**Issue by villar35738** [SimpleBrowserDotNet/SimpleBrowser#259]
I used to use selenium with Firefox and there I can use something like this:

browser.SwitchTo().Window(browser.WindowHandles[0]);

**Comment by kevingy** [comment]
I absolutely hate that it works this way, but use the Browser.Windows property to get the collection of all browsers. Then, you can go through the IEnumerable to get what you're looking for.

**Comment by kevingy** [comment]
@villar35738 Did this answer your question?

**Comment by kevingy** [comment]
Stale issue. No response from requestor.
