### ISSUE TITLE
Problem submitting a form with two elements with the same name

### ISSUE THREAD

**Issue by kevingy** [SimpleBrowserDotNet/SimpleBrowser#52]
Consider the following HTML:

```html
<!DOCTYPE html>
<html>
<body>
<form action="http://symlink.dk/code/php/submit/">
<input type="text" name="input1" value="123"><br>
<input type="text" name="input1" value="456">
<input type="submit">
</form>
</body>
</html>
```
Note that the example form contains two elements with the same name.

When submitted, SimpleBrowser sends the "input1" key with the value "123,456" - a CSV representation of the two input values. At first, I thought this was correct. However, after testing and experimentation, this appears not to be correct. If the form is submitted using Chrome, FireFox, Safari, or IE, the "input1" key value is "456" - the last instance of "input1" on the page. If the first "input1" has a value and the second "input1" has no value, the value of input1 on submit is "", still the value of the last instance of "input1" on the page.

Looking at the HTML4 and HTML5 specifications, I can't find a reference to what *should* be submitted. If four of the top browsers work this way, it's at least the *de facto* way it should work.

**Comment by kevingy** [comment]
This issue needs more attention. The submitted fix works properly if the two named inputs are of the same type. If the inputs are of different types, it looks like they should both be submitted. That is, at least, the behavior of Chrome.

**Comment by kevingy** [comment]
Additional testing shows that this issue is/was correctly addressed.

**Comment by micahhahn** [comment]
I'm running into issues when I have multiple inputs of type checkbox with the same name.  The behavior that Chrome and friends are giving me is to submit every single value that is selected, whereas SimpleBrowser appears to only submit the last checkbox that is checked.  I'm working around this by adding these values via `ExtraFormValues`, but it is inconvenient and probably a bug.

**Comment by kevingy** [comment]
@micahhahn 
I'll set up a test that covers this case. In the meantime, can you share the URL of the page that you are using to produce the problem? Thanks!

**Comment by micahhahn** [comment]
@kevingy 
Thanks for the quick response on this.  Unfortunately, I can't give you the URL as the website is password protected.

**Comment by kevingy** [comment]
@micahhahn
If you can't provide the URL, can you provide the HTML? Even if it's just the form tag and the checkbox input tags?

Here's my test:
``` HTML
<form action="http://symlink.dk/code/php/submit/" id="form1" method="post">
<input type="checkbox" name="cbx" value='1' />1<br />
<input type="checkbox" name="cbx" value='2' />2<br />
<input type="checkbox" name="cbx" value='3' />3<br />
<input type="checkbox" name="cbx" value='4' />4<br />
<input type="checkbox" name="cbx" value='5' />5<br />
<input type="submit" name="submit">
</form>
```

When I submit this form via Chrome, the result is cbx=5. That is, Chrome is only submitting the last check box, not all five check boxes. This is the SimpleBrowser behavior as well.

**Comment by kevingy** [comment]
Oh, I also checked all of the check boxes before submitting the form in Chrome.

**Comment by micahhahn** [comment]
The form I'm working with looks like something like what's below:

```html
<form name="_ctl0" method="post" action="selectreportsform.aspx" id="_ctl0">
    <tr>
        <td class="EditForm-Normal" valign="top">
            <input type="checkbox" name="fields" value="ISSN" checked="" />ISSN/ISBN&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="Title" checked="" />Title&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="Turnaways" />Turnaways&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="FullText" />Total Full Text Requests&nbsp;&nbsp;&nbsp;
            <br />
        </td>
        <td class="EditForm-Normal" valign="top">
            <input type="checkbox" name="fields" value="PdfFTCount" checked="" />PDF Full Text Requests&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="HtmlFTCount" checked="" />HTML Full Text Requests&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="EBookFTCount" />eBook Online Full Text Requests&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="EBookDownloadCount" />eBook Offline/Download Requests&nbsp;&nbsp;&nbsp;
            <br />
        </td>
        <td class="EditForm-Normal" valign="top">
            <input type="checkbox" name="fields" value="AudioBookDownloadCount" />Audiobook Download Requests&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="ImageCount" checked="" />Image/Video Requests&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="AudioCount" />Audio Requests&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="AbstractCount" checked="" />Abstract Requests&nbsp;&nbsp;&nbsp;
            <br />
        </td>
        <td class="EditForm-Normal" valign="top">
            <input type="checkbox" name="fields" value="SmartLinkCount" checked="" />SmartLink To Requests&nbsp;&nbsp;&nbsp;
            <br />
            <input type="checkbox" name="fields" value="CustomLinkCount" checked="" />CustomLink Requests&nbsp;&nbsp;&nbsp;
            <br />
        </td>
    </tr>
</form>
```

It's entirely possible that the webpage is using javascript to manually create those post fields (although I can't imagine why it would).  I'll look into it.

**Comment by twpol** [comment]
@kevingy That seems to be a bug with the reporting on the site you're submitting to; if I look in the dev tools in Internet Explorer, for example, it shows the request is sending `cbx=1&cbx=3&cbx=4&submit=Submit+Query` (I selected 1, 3 and 4) but the site reports `cbx` as just 4.

**Comment by kevingy** [comment]
@twpol

Wow! Confirmed. There is a bug in the form handler on Symlink.dk. That means this has been broken for a long, long time. I'll get a fix in this afternoon.

Good catch!

**Comment by kevingy** [comment]
A change to address this issue has been submitted. I just backed out the original change to fix a bug that apparently didn't exist.
