### ISSUE TITLE
Replace the Dependencies folder with NuGet packages.

### ISSUE THREAD

**Issue by jbuedel** [SimpleBrowserDotNet/SimpleBrowser#76]
The [Dependencies](https://github.com/axefrog/SimpleBrowser/tree/master/Dependencies) folder contains reference assemblies that as far as I can tell are all available on NuGet already.  Converting all those file assembly references to NuGet package references will, among other things, simply the .nuspec file by allowing the build to automatically determine the files to pack.

**Comment by kevingy** [comment]
This issue ancient, but now that we're on .NET 4.5 and Mono now supports NuGet, I think that this can now be completed. I'm working on it.

**Comment by kevingy** [comment]
Update: Mono supports NuGet, but it does not allow the user to select a specific version of the library nor does it examine all of the versions of a package and select the newest version of the package that works given the project dependencies. I have been able to updated everything except for the version of Moq that's used by the unit test project. The newest version of Moq (approximately version 4.10) looks like it only supports .NET Standard. We would need to use a version that works with .NET Framework 4.5 - approximately Moq version 4.7. (This is an upgrade from the previous version of Moq that we were using - 4.0.108.)

If I can convince MonoDevelop to let me pull Moq 4.7 from NuGet, I think this is done.
